<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public $withinTransaction = false;

    public function up(): void
    {
        if (DB::getDriverName() === 'pgsql') {
            $statements = [
                <<<'SQL'
CREATE TABLE IF NOT EXISTS "push_tokens" (
    "id" bigint generated by default as identity primary key
)
SQL,
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "user_id" bigint',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "token" varchar(255)',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "platform" varchar(20)',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "device_id" varchar(255)',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "device_name" varchar(255)',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "app_version" varchar(100)',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "last_used_at" timestamp(0) without time zone',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "revoked_at" timestamp(0) without time zone',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "created_at" timestamp(0) without time zone',
                'ALTER TABLE "push_tokens" ADD COLUMN IF NOT EXISTS "updated_at" timestamp(0) without time zone',
                'ALTER TABLE "push_tokens" ALTER COLUMN "user_id" SET NOT NULL',
                'ALTER TABLE "push_tokens" ALTER COLUMN "token" SET NOT NULL',
                'CREATE UNIQUE INDEX IF NOT EXISTS "push_tokens_token_unique" ON "push_tokens" ("token")',
                'CREATE INDEX IF NOT EXISTS "push_tokens_platform_index" ON "push_tokens" ("platform")',
                'CREATE INDEX IF NOT EXISTS "push_tokens_device_id_index" ON "push_tokens" ("device_id")',
                'CREATE INDEX IF NOT EXISTS "push_tokens_user_id_revoked_at_index" ON "push_tokens" ("user_id", "revoked_at")',
            ];

            foreach ($statements as $statement) {
                DB::statement($statement);
            }

            DB::unprepared(<<<'SQL'
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'push_tokens_user_id_foreign'
    ) THEN
        ALTER TABLE "push_tokens"
            ADD CONSTRAINT "push_tokens_user_id_foreign"
            FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
    END IF;
END
$$;
SQL);

            return;
        }

        Schema::create('push_tokens', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->string('token')->unique();
            $table->string('platform', 20)->nullable()->index();
            $table->string('device_id')->nullable()->index();
            $table->string('device_name')->nullable();
            $table->string('app_version', 100)->nullable();
            $table->timestamp('last_used_at')->nullable();
            $table->timestamp('revoked_at')->nullable();
            $table->timestamps();

            $table->index(['user_id', 'revoked_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('push_tokens');
    }
};
